// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionDocumentos.API.Data;

#nullable disable

namespace SistemaGestionDocumentos.API.Migrations
{
    [DbContext(typeof(SistemaGestionDocumentosDbContext))]
    [Migration("20251127205421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.AuditoriaAccion", b =>
                {
                    b.Property<int>("IdentificadorRegistroAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorRegistroAuditoria"));

                    b.Property<string>("DescripcionAccionRealizada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetallesAdicionalesAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIPDelDispositivoAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraExactaAccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdentificadorDocumentoRelacionadoAccion")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorUsuarioQueRealizaAccion")
                        .HasColumnType("int");

                    b.HasKey("IdentificadorRegistroAuditoria");

                    b.HasIndex("IdentificadorUsuarioQueRealizaAccion");

                    b.ToTable("AuditoriaAccionDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.Documento", b =>
                {
                    b.Property<int>("IdentificadorDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorDocumento"));

                    b.Property<string>("DescripcionAdicionalesDelDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoActualDelDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSubidaDelDocumento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaModificacionDelDocumento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificadorUsuarioPropietarioDelDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NombreDescriptivoDelDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroVersionActualDelDocumento")
                        .HasColumnType("int");

                    b.Property<string>("RutaFisicaDelArchivoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificadorDocumento");

                    b.HasIndex("IdentificadorUsuarioPropietarioDelDocumento");

                    b.ToTable("DocumentosDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.NotificacionPendiente", b =>
                {
                    b.Property<int>("IdentificadorNotificacionPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorNotificacionPendiente"));

                    b.Property<string>("AsuntoNotificacionCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoMensajeNotificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacionNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdentificadorDocumentoRelacionadoNotificacion")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorUsuarioReceptorNotificacion")
                        .HasColumnType("int");

                    b.Property<bool>("IndicadorNotificacionLeidaONo")
                        .HasColumnType("bit");

                    b.Property<string>("TipoNotificacionEnviar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificadorNotificacionPendiente");

                    b.HasIndex("IdentificadorDocumentoRelacionadoNotificacion");

                    b.HasIndex("IdentificadorUsuarioReceptorNotificacion");

                    b.ToTable("NotificacionesPendientesDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdentificadorUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorUsuario"));

                    b.Property<string>("ContraseñaHashDelUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoDelUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacionDelUsuario")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IndicadorUsuarioActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompletoDelUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolDelUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificadorUsuario");

                    b.ToTable("UsuariosDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.VersionDocumento", b =>
                {
                    b.Property<int>("IdentificadorVersionDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorVersionDocumento"));

                    b.Property<string>("ComentariosDelCambioDeVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacionDelVersionDocumento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificadorDocumentoPerteneceVersion")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivoDelVersionDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSecuencialDelVersionDocumento")
                        .HasColumnType("int");

                    b.Property<string>("RutaFisicaDelArchivoVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificadorVersionDocumento");

                    b.HasIndex("IdentificadorDocumentoPerteneceVersion");

                    b.ToTable("VersionesDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.WorkflowAprobacion", b =>
                {
                    b.Property<int>("IdentificadorRegistroAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorRegistroAprobacion"));

                    b.Property<string>("ComentariosDelAprobadorDelDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoActualDelFlujoAprobacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAccionAprobacionDelDocumento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificadorDocumentoAprobar")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorUsuarioAprobadorDelDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NivelPrioridadDelDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificadorRegistroAprobacion");

                    b.HasIndex("IdentificadorDocumentoAprobar");

                    b.HasIndex("IdentificadorUsuarioAprobadorDelDocumento");

                    b.ToTable("WorkflowAprobacionDelSistema");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.AuditoriaAccion", b =>
                {
                    b.HasOne("SistemaGestionDocumentos.API.Models.Usuario", "UsuarioQueRealiza")
                        .WithMany("AccionesAuditoriasDelUsuario")
                        .HasForeignKey("IdentificadorUsuarioQueRealizaAccion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UsuarioQueRealiza");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.Documento", b =>
                {
                    b.HasOne("SistemaGestionDocumentos.API.Models.Usuario", "UsuarioPropietarioDelDocumento")
                        .WithMany("DocumentosDelUsuario")
                        .HasForeignKey("IdentificadorUsuarioPropietarioDelDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioPropietarioDelDocumento");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.NotificacionPendiente", b =>
                {
                    b.HasOne("SistemaGestionDocumentos.API.Models.Documento", "DocumentoRelacionado")
                        .WithMany("NotificacionesDelDocumento")
                        .HasForeignKey("IdentificadorDocumentoRelacionadoNotificacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumentos.API.Models.Usuario", "UsuarioReceptor")
                        .WithMany("NotificacionesDelUsuario")
                        .HasForeignKey("IdentificadorUsuarioReceptorNotificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DocumentoRelacionado");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.VersionDocumento", b =>
                {
                    b.HasOne("SistemaGestionDocumentos.API.Models.Documento", "DocumentoAlQuePerteneceLaVersion")
                        .WithMany("VersionesDelDocumento")
                        .HasForeignKey("IdentificadorDocumentoPerteneceVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoAlQuePerteneceLaVersion");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.WorkflowAprobacion", b =>
                {
                    b.HasOne("SistemaGestionDocumentos.API.Models.Documento", "DocumentoEnAprobacion")
                        .WithMany("FlujosAprobacionDelDocumento")
                        .HasForeignKey("IdentificadorDocumentoAprobar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumentos.API.Models.Usuario", "UsuarioQueAprueba")
                        .WithMany("AprobacionesDelUsuario")
                        .HasForeignKey("IdentificadorUsuarioAprobadorDelDocumento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DocumentoEnAprobacion");

                    b.Navigation("UsuarioQueAprueba");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.Documento", b =>
                {
                    b.Navigation("FlujosAprobacionDelDocumento");

                    b.Navigation("NotificacionesDelDocumento");

                    b.Navigation("VersionesDelDocumento");
                });

            modelBuilder.Entity("SistemaGestionDocumentos.API.Models.Usuario", b =>
                {
                    b.Navigation("AccionesAuditoriasDelUsuario");

                    b.Navigation("AprobacionesDelUsuario");

                    b.Navigation("DocumentosDelUsuario");

                    b.Navigation("NotificacionesDelUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
